try{
    console.log(c+b);
    
}catch(err){

    console.log(err);
    console.log("There was an error");
    
    
}
console.log("the program does not stop");
